version: '3.8'
services:
  suml_streamlit_dev:
    container_name: suml_streamlit_dev
    # stdin_open: true
    # tty: true
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8501:8501"
    volumes:
      - ../:/usr/suml/frontend/:ro
    env_file:
      - .env