version: '3.8'
services:
  suml_react_dev:
    container_name: suml_react_dev
    # stdin_open: true
    # tty: true
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../src:/usr/suml/frontend/src:ro
    env_file:
      - .env